"use client";
import { useEffect, useRef, useState } from "react";
import { getFinanceCustomerCredits, registerFinanceCustomerCredit, applyFinanceCustomerCredit, reverseFinanceCustomerCredit, type FinanceCustomerCredit, type FinanceCustomerCreditPage, type FinanceAllocationPage, type FinanceWorkspaceContext } from "@/lib/api";
import { RecordBrowser } from "@/components/finance-allocation-workspace";

type Row = FinanceAllocationPage["records"][number];
const money = (v: number) => new Intl.NumberFormat("es-CL", { style: "currency", currency: "CLP", maximumFractionDigits: 0 }).format(v);
const kinds: Record<string, string> = { ADVANCE: "Anticipo", OVERPAYMENT: "Sobrepago", REMAINDER: "Remanente" };
export function FinanceCustomerCredits({ context, canManage, disabled, onBusy, onChanged }: { context: FinanceWorkspaceContext; canManage: boolean; disabled: boolean; onBusy: (v: boolean) => void; onChanged: () => Promise<void> }) {
  const [view, setView] = useState<FinanceCustomerCreditPage | null>(null), [page, setPage] = useState(1), [query, setQuery] = useState("");
  const [busy, setBusy] = useState(false), [message, setMessage] = useState(""), [revision, setRevision] = useState(0);
  const [movement, setMovement] = useState<Row | null>(null), [name, setName] = useState(""), [rut, setRut] = useState(""), [kind, setKind] = useState("ADVANCE"), [reason, setReason] = useState("");
  const [selected, setSelected] = useState<FinanceCustomerCredit | null>(null), [allocations, setAllocations] = useState<Array<{ row: Row; amount: string }>>([]), [date, setDate] = useState("");
  const lock = useRef(false), generation = useRef(0);
  const locked = busy || disabled || !canManage;
  async function load() { const seq = ++generation.current; try { const result = await getFinanceCustomerCredits(page, query); if (seq === generation.current) setView(result); } catch (e) { if (seq === generation.current) { setView(null); setMessage(e instanceof Error ? e.message : "No se pudieron consultar saldos."); } } }
  useEffect(() => { void load(); return () => { generation.current++; }; }, [page, revision]);
  async function run(action: () => Promise<unknown>, success: string) {
    if (lock.current || locked) return; lock.current = true; setBusy(true); onBusy(true); setMessage("");
    try { await action(); setMovement(null); setSelected(null); setAllocations([]); setReason(""); setRevision((v) => v + 1); setMessage(success); await onChanged(); }
    catch (e) { setMessage(e instanceof Error ? e.message : "No se pudo registrar. Actualiza antes de reintentar."); setSelected(null); setAllocations([]); setRevision((v) => v + 1); }
    finally { lock.current = false; setBusy(false); onBusy(false); }
  }
  function reverse(id: string, application: boolean) {
    const value = window.prompt(application ? "Motivo para revertir la aplicación. Se restablecen la deuda y el saldo a favor, sin generar un ingreso nuevo." : "Motivo para revertir el origen. El abono vuelve a estar disponible; primero deben revertirse todas sus aplicaciones.");
    if (value === null) return; if (value.trim().length < 10) { setMessage("El motivo debe tener al menos 10 caracteres."); return; }
    void run(() => reverseFinanceCustomerCredit(id, value, application), "Reversa verificada y guardada, conservando el historial.");
  }
  const total = allocations.reduce((s, a) => s + Number(a.amount), 0);
  return <section className="finance-card finance-customer-credits">
    <h2>Anticipos, sobrepagos y remanentes</h2>
    <p>Un abono se registra una sola vez. Si aún no tiene factura o excede la deuda, consérvalo como saldo a favor del cliente y aplica sólo lo necesario. El resto queda disponible; no es una venta nueva ni un segundo ingreso bancario.</p>
    <p className="finance-note">Esta bandeja muestra saldos de todos los períodos de la empresa. La selección de abonos usa el período y cuenta activos. Operación en CLP, con identificación del cliente por RUT y aprobación humana.</p>
    {message ? <p role="status" className="finance-note">{message}</p> : null}{busy ? <p role="status">Guardando operación auditada…</p> : null}
    <details><summary>Registrar un abono como saldo a favor</summary>
      <RecordBrowser context={context} kind="movements" revision={revision} disabled={locked} selected={movement ? [movement.id] : []} onSelect={(row) => { setSelected(null); setMovement(row); setReason(""); }} />
      {movement ? <div className="finance-coverage-fields"><p className="finance-coverage-evidence"><strong>{movement.title} · {money(Number(movement.data?.amount || 0))}</strong><br />Se reserva el abono completo. A continuación podrás aplicarlo a las facturas del cliente y conservar el excedente.</p>
        <label>Nombre / razón social<input value={name} maxLength={200} disabled={locked} onChange={(e) => setName(e.target.value)} /></label><label>RUT del cliente<input value={rut} maxLength={14} disabled={locked} onChange={(e) => setRut(e.target.value)} /></label>
        <label>Origen del saldo<select value={kind} disabled={locked} onChange={(e) => setKind(e.target.value)}>{Object.entries(kinds).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label>
        <label className="finance-coverage-evidence">Motivo y respaldo de identificación<textarea value={reason} maxLength={1000} disabled={locked} onChange={(e) => setReason(e.target.value)} /></label>
        <button type="button" className="primary-btn" disabled={locked || !name.trim() || !rut.trim() || reason.trim().length < 10} onClick={() => { if (window.confirm("¿Reservar este abono para el cliente indicado? No se pagará ninguna factura todavía.")) void run(() => registerFinanceCustomerCredit({ movementId: movement.id, customerName: name, customerRut: rut, kind, reason }), "Saldo a favor registrado. Selecciónalo en la lista para aplicarlo a facturas; no se creó ningún ingreso adicional."); }}>Confirmar saldo a favor</button>
      </div> : null}
    </details>
    <div className="finance-review-toolbar"><label>Buscar cliente / RUT<input disabled={busy} value={query} onChange={(e) => setQuery(e.target.value)} /></label><button type="button" disabled={busy} onClick={() => { setSelected(null); if (page !== 1) setPage(1); else void load(); }}>Buscar / actualizar</button><strong>Disponible: {money(view?.availableAmount || 0)}</strong><span>{view?.reviewCount || 0} saldos requieren revisión</span></div>
    <div className="finance-review-table-wrap"><table><thead><tr><th>Cliente / origen</th><th>Recibido</th><th>Aplicado</th><th>Disponible</th><th>Acciones</th></tr></thead><tbody>{view?.records.map((credit) => <tr key={credit.id}><td><strong>{credit.data.customerName}</strong><small>{credit.data.customerRut} · {kinds[credit.data.kind] || "Saldo a favor"} · {credit.data.transactionDate}</small>{credit.status === "REVERSED" ? <small>Origen revertido</small> : null}{credit.ledger.errors.map((e) => <p key={e} role="alert">{e}</p>)}<details><summary>Historial de aplicaciones ({credit.ledger.applications.length})</summary><p>Origen: {credit.data.reason}</p>{credit.ledger.applications.map((a) => <div key={a.id}><p>{String(a.data?.applicationDate)} · {money(Number(a.data?.amount))} · {a.status === "REVERSED" ? "Revertida" : "Aplicada"}</p><p>{String(a.data?.reason || "")}</p>{Array.isArray(a.data?.allocations) ? (a.data.allocations as Array<{ invoiceId: string; documentTitle: string; amount: number }>).map((entry) => <p key={entry.invoiceId}>{entry.documentTitle} · {money(entry.amount)}</p>) : null}{a.status === "APPLIED" ? <button type="button" className="finance-danger-button" disabled={locked || !credit.ledger.valid} onClick={() => reverse(a.id, true)}>Revertir aplicación</button> : <p>{String(a.data?.reversalReason || "")}</p>}</div>)}</details></td>
      <td>{money(credit.data.amount)}</td><td>{credit.ledger.valid ? money(credit.ledger.applied) : "Por revisar"}</td><td>{credit.ledger.valid ? money(credit.ledger.available) : "Por revisar"}</td><td><button type="button" disabled={locked || !credit.ledger.valid || credit.ledger.available <= 0} onClick={() => { setSelected(credit); setMovement(null); setAllocations([]); setReason(""); setDate(""); }}>Aplicar a facturas</button><button type="button" className="finance-danger-button" disabled={locked || !credit.ledger.valid || credit.status === "REVERSED" || credit.ledger.applications.some((a) => a.status === "APPLIED")} onClick={() => reverse(credit.id, false)}>Revertir origen</button></td></tr>)}</tbody></table></div>
    {!view?.total ? <p>No hay saldos a favor con estos filtros.</p> : null}
    <div className="finance-review-toolbar"><button type="button" disabled={busy || page <= 1} onClick={() => { setSelected(null); setPage(page - 1); }}>Anterior</button><span>Página {page} de {view?.pages || 1}</span><button type="button" disabled={busy || !view || page >= view.pages} onClick={() => { setSelected(null); setPage(page + 1); }}>Siguiente</button></div>
    {selected ? <div className="finance-bank-review"><h3>Aplicar saldo de {selected.data.customerName}</h3><p>Disponible {money(selected.ledger.available)}. Sólo se muestran facturas del mismo RUT. La fecha de aplicación debe ser igual o posterior al abono y a la emisión.</p><label>Fecha efectiva de aplicación<input type="date" disabled={locked} value={date} onChange={(e) => { setDate(e.target.value); setAllocations([]); }} /></label>
      {date ? <RecordBrowser key={`${selected.id}:${date}`} context={{ ...context, period: date.slice(0, 7), accountKey: "", currency: "CLP" }} customerRut={selected.data.customerRut} kind="invoices" revision={revision} disabled={locked} selected={allocations.map((a) => a.row.id)} onSelect={(row) => setAllocations((items) => items.some((a) => a.row.id === row.id) ? items.filter((a) => a.row.id !== row.id) : items.length < 100 ? [...items, { row, amount: String(Math.min(Number(row.financial?.balance || 0), Math.max(0, selected.ledger.available - items.reduce((s, a) => s + Number(a.amount), 0)))) }] : items)} /> : null}
      <div className="finance-coverage-fields">{allocations.map((item) => <label key={item.row.id}>{item.row.title} · deuda {money(Number(item.row.financial?.balance))}<input type="number" min={1} step={1} max={item.row.financial?.balance} disabled={locked} value={item.amount} onChange={(e) => setAllocations((items) => items.map((a) => a.row.id === item.row.id ? { ...a, amount: e.target.value } : a))} /></label>)}<label className="finance-coverage-evidence">Motivo y respaldo de aplicación<textarea disabled={locked} maxLength={1000} value={reason} onChange={(e) => setReason(e.target.value)} /></label></div>
      <p>Aplicar: {money(total)} · Remanente: {money(selected.ledger.available - total)}</p><button type="button" className="primary-btn" disabled={locked || !date || reason.trim().length < 10 || total <= 0 || total > selected.ledger.available || allocations.some((a) => !Number.isSafeInteger(Number(a.amount)) || Number(a.amount) <= 0 || Number(a.amount) > Number(a.row.financial?.balance))} onClick={() => { if (window.confirm(`¿Aplicar ${money(total)}? Quedarán ${money(selected.ledger.available - total)} disponibles.`)) void run(() => applyFinanceCustomerCredit(selected.id, { expectedVersion: selected.data.version, allocations: allocations.map((a) => ({ invoiceId: a.row.id, amount: Number(a.amount) })), applicationDate: date, reason }), "Aplicación guardada. Facturas y saldo a favor actualizados sin duplicar el ingreso del banco."); }}>Confirmar aplicación</button><button type="button" disabled={busy} onClick={() => setSelected(null)}>Cancelar</button>
    </div> : null}
  </section>;
}
