"use client";
import { useRef, useState } from "react";
import { saveFinanceBankAccount, type FinanceBankAccount } from "@/lib/api";

export function FinanceBankAccounts({ accounts, banks, disabled, canManage, onBusy, onChanged }: { accounts: FinanceBankAccount[]; banks: Array<{ key: string; name: string }>; disabled: boolean; canManage: boolean; onBusy: (v: boolean) => void; onChanged: () => Promise<void> }) {
  const [form, setForm] = useState({ accountAlias: "", bankKey: "", accountLast4: "", accountType: "Cuenta corriente", currency: "CLP" });
  const [error, setError] = useState(""), [message, setMessage] = useState(""); const lock = useRef(false);
  async function run(action: () => Promise<unknown>) {
    if (lock.current || disabled || !canManage) return; lock.current = true; onBusy(true); setError(""); setMessage("");
    try { await action(); await onChanged(); setMessage("Cuenta guardada. El historial de movimientos se conserva."); } catch (e) { setError(e instanceof Error ? e.message : "No se pudo guardar la cuenta."); } finally { lock.current = false; onBusy(false); }
  }
  return <article className="finance-card finance-bank-accounts"><details><summary>Cuentas bancarias y monedas ({accounts.length})</summary><p>Registra cada cuenta una vez. Sólo se guardan sus últimos cuatro dígitos; nunca claves bancarias. El identificador interno permanece estable aunque cambies el nombre. Desactivar no borra sus movimientos.</p>
    {error && <p role="alert" className="finance-note">{error}</p>}{message && <p role="status">{message}</p>}
    <div className="finance-review-table-wrap"><table><thead><tr><th>Cuenta</th><th>Banco / identificación</th><th>Moneda</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{accounts.map((a) => <tr key={a.id}><td>{a.accountAlias}</td><td>{a.bank} · ****{a.accountLast4}</td><td>{a.currency}</td><td>{a.status === "ACTIVE" ? "Activa" : "Inactiva"}</td><td><button type="button" disabled={disabled || !canManage} onClick={() => { const name = window.prompt("Nombre de la cuenta (no cambia su identidad):", a.accountAlias); if (name !== null) void run(() => saveFinanceBankAccount({ accountAlias: name, status: a.status, version: a.version }, a.id)); }}>Cambiar nombre</button><button type="button" disabled={disabled || !canManage} onClick={() => { if (window.confirm(a.status === "ACTIVE" ? "¿Desactivar esta cuenta para nuevas cargas? Su historial se conserva." : "¿Reactivar esta cuenta?")) void run(() => saveFinanceBankAccount({ accountAlias: a.accountAlias, status: a.status === "ACTIVE" ? "INACTIVE" : "ACTIVE", version: a.version }, a.id)); }}>{a.status === "ACTIVE" ? "Desactivar" : "Reactivar"}</button></td></tr>)}</tbody></table></div>
    {canManage && <form onSubmit={(e) => { e.preventDefault(); void run(async () => { await saveFinanceBankAccount(form); setForm({ ...form, accountAlias: "", accountLast4: "" }); }); }}><fieldset disabled={disabled} className="finance-bank-mapping-fields" style={{ border: 0 }}><legend>Nueva cuenta</legend><label>Nombre<input required minLength={3} maxLength={100} value={form.accountAlias} placeholder="Ej.: Cuenta operativa USD" onChange={(e) => setForm({ ...form, accountAlias: e.target.value })} /></label><label>Banco<select required value={form.bankKey} onChange={(e) => setForm({ ...form, bankKey: e.target.value })}><option value="">Selecciona un banco</option>{banks.map((b) => <option key={b.key} value={b.key}>{b.name}</option>)}</select></label><label>Últimos cuatro dígitos<input required inputMode="numeric" pattern="[0-9]{4}" maxLength={4} value={form.accountLast4} onChange={(e) => setForm({ ...form, accountLast4: e.target.value })} /></label><label>Tipo<select value={form.accountType} onChange={(e) => setForm({ ...form, accountType: e.target.value })}>{["Cuenta corriente", "Cuenta vista", "Cuenta de ahorro"].map((s) => <option key={s}>{s}</option>)}</select></label><label>Moneda<select value={form.currency} onChange={(e) => setForm({ ...form, currency: e.target.value })}>{["CLP", "USD", "EUR", "UF"].map((s) => <option key={s}>{s}</option>)}</select></label><button className="primary-btn" type="submit">Registrar cuenta</button></fieldset></form>}
    <p>Registrar una cuenta no conecta al banco por API. La consulta e importación conservan la moneda original; no se aplican tipos de cambio. Las operaciones de conciliación y cierre actuales admiten CLP.</p>
  </details></article>;
}
